esphome:
  name: esphome-web-a949c0
  friendly_name: Billy S3
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
api:
ota:
  - platform: esphome

external_components:
  source:
    type: git
    url: https://github.com/Cian911/billy-ai
    ref: main
    components: [speaker_tap]

# ---------- I2S Buses ----------
i2s_audio:
  # Mic bus
  - id: bus0
    i2s_lrclk_pin: GPIO9 # was 25 on WROOM-32
    i2s_bclk_pin: GPIO10 # was 26 (reserved on S3)

  # Speaker bus
  - id: i2s_out
    i2s_lrclk_pin: GPIO12 # was 18
    i2s_bclk_pin: GPIO13 # was 19 (USB D- on S3)

# ---------- Speaker + Tap ----------
speaker:
  - platform: i2s_audio
    id: spk_hw
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO11 # was 21

  - platform: speaker_tap
    id: spk_tap
    sink: spk_hw
    gain: 6.0
    attack_ms: 8
    release_ms: 120
    publish_interval: 80ms
    sample_rate: 22050
    level:
      id: audio_level
      name: "Audio Level"
      on_value:
        then:
          - lambda: |-
              static float ema = 0.0f;
              const float alpha = 0.25f;
              float v = x;
              ema = (1.0f - alpha) * ema + alpha * v;

              const float OPEN_TH   = 6.0f;
              const float CLOSE_TH  = 6.0f;
              const uint32_t REFRESH_MS = 140;
              const uint32_t MIN_GAP_MS = 40;
              const uint32_t FAILSAFE_MS = 900;

              static bool open = false;
              static uint32_t last_ms = 0;
              uint32_t now = millis();

              if (!open) {
                if (ema > OPEN_TH && (now - last_ms > MIN_GAP_MS)) {
                  id(mouth_open_pulse).execute();
                  open = true;
                  last_ms = now;
                }
              } else {
                if (ema > OPEN_TH) {
                  if (now - last_ms > REFRESH_MS) {
                    id(mouth_open_keep).execute();
                    last_ms = now;
                  }
                } else if (ema < CLOSE_TH) {
                  id(mouth_close_pulse).execute();
                  open = false;
                  last_ms = now;
                }
                if (open && (now - last_ms > FAILSAFE_MS)) {
                  id(mouth_close_pulse).execute();
                  open = false;
                  last_ms = now;
                }
              }

# ---------- Microphone ----------
microphone:
  - platform: i2s_audio
    id: mic
    i2s_audio_id: bus0
    adc_type: external
    i2s_din_pin: GPIO8 # Was 33
    channel: left

# ---------- Voice Assistant ----------
voice_assistant:
  microphone: mic
  id: va
  noise_suppression_level: 0
  auto_gain: 1dBFS
  volume_multiplier: 8.0
  use_wake_word: false
  speaker: spk_tap

  on_error:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - switch.turn_off: use_wake_word
          - switch.turn_on: use_wake_word

  on_client_connected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.start_continuous:

  on_client_disconnected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:

  on_wake_word_detected:
    - light.turn_on: status_led
    - lambda: |-
        auto call = id(head_motor).turn_on();
        call.set_direction(FanDirection::FORWARD);
        call.set_speed(100);
        call.perform();

  on_stt_end:
    - light.turn_off: status_led
    - lambda: |-
        auto call = id(head_motor).turn_off();
        call.set_direction(FanDirection::REVERSE);
        call.set_speed(80);
        call.perform();

binary_sensor:
  - platform: status
    name: API Connection
    id: api_connection
    filters:
      - delayed_on: 1s
    on_press:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - voice_assistant.start_continuous:
    on_release:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - voice_assistant.stop:

switch:
  - platform: restart
    name: Restart Billy
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    chipset: WS2812 # onboard RGB on ESP32-S3 DevKitC-1 is WS2812
    pin: GPIO38 # common on DevKitC-1; some revs use GPIO38
    num_leds: 1
    rgb_order: GRB # WS2812s are typically GRB
    default_transition_length: 0s

# ---------- Outputs ----------
output:
  - platform: ledc
    pin: GPIO4 # was 32
    id: motor_forward_pin
    frequency: 20000 Hz

  - platform: ledc
    pin: GPIO5 # was 14
    id: motor_reverse_pin
    frequency: 20000 Hz

  - platform: ledc
    frequency: 20000 Hz
    pin: GPIO16 # was 23
    id: motor2_forward_pin

  - platform: ledc
    pin: GPIO17 # was 22
    frequency: 20000 Hz
    id: motor2_reverse_pin

# ---------- H-Bridge Fans ----------
fan:
  - platform: hbridge
    id: mouth_motor
    name: "Billy Bass Mouth"
    pin_a: motor_forward_pin
    pin_b: motor_reverse_pin
    decay_mode: FAST
    speed_count: 100

  - platform: hbridge
    id: head_motor
    name: "Billy Bass Head"
    pin_a: motor2_forward_pin
    pin_b: motor2_reverse_pin
    decay_mode: SLOW
    speed_count: 100

  - platform: hbridge
    id: tail_motor
    name: "Billy Bass Tail"
    pin_a: motor2_reverse_pin
    pin_b: motor2_forward_pin
    decay_mode: SLOW
    speed_count: 10

globals:
  - id: mouth_is_open
    type: bool
    restore_value: no
    initial_value: "false"
  - id: last_pulse_ms
    type: uint32_t
    restore_value: no
    initial_value: "0"

script:
  - id: mouth_open_pulse
    mode: restart
    then:
      - lambda: |-
          auto call = id(mouth_motor).turn_on();
          call.set_direction(FanDirection::FORWARD);
          call.set_speed(80);
          call.perform();
      - delay: 110ms
      - lambda: |-
          id(mouth_motor).turn_off().perform();

  - id: mouth_open_keep
    mode: restart
    then:
      - lambda: |-
          auto call = id(mouth_motor).turn_on();
          call.set_direction(FanDirection::FORWARD);
          call.set_speed(80);
          call.perform();
      - delay: 60ms
      - lambda: |-
          id(mouth_motor).turn_off().perform();

  - id: mouth_close_pulse
    mode: restart
    then:
      - lambda: |-
          auto call = id(mouth_motor).turn_on();
          call.set_direction(FanDirection::REVERSE);
          call.set_speed(75);
          call.perform();
      - delay: 160ms
      - lambda: |-
          id(mouth_motor).turn_off().perform();

sensor:
  - platform: template
    id: audio_level_router
    update_interval: never
    on_value:
      then:
        - lambda: |-
            return;

button:
  - platform: template
    name: "Head FWD 1s"
    on_press:
      - lambda: |-
          auto c = id(head_motor).turn_on();
          c.set_direction(FanDirection::FORWARD);
          c.set_speed(100);
          c.perform();
      - delay: 1s
      - lambda: "id(head_motor).turn_off().perform();"

  - platform: template
    name: "Head REV 1s"
    on_press:
      - lambda: |-
          auto c = id(head_motor).turn_on();
          c.set_direction(FanDirection::REVERSE);
          c.set_speed(100);
          c.perform();
      - delay: 1s
      - lambda: "id(head_motor).turn_off().perform();"
