esphome:
  name: esphome-web-4f6da4
  friendly_name: Billy4
  min_version: 2025.5.0
  name_add_mac_suffix: false
  on_boot:
    priority: 800
    then:
      - lambda: |-
          id(mouth_motor).state;

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: local
      path: components

switch:
  - platform: template
    name: "Test Mouth Motor"
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(mouth_motor)->turn_on().perform();
    turn_off_action:
      - lambda: |-
          id(mouth_motor)->turn_off().perform();

# ========== I2S AUDIO ==========
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26
  # - id: i2s_mic
  #   i2s_lrclk_pin: GPIO32    # WS from INMP441
  #   i2s_bclk_pin: GPIO33     # SCK from INMP441

# ========== AUDIO OUTPUT ==========
media_player:
  - platform: i2s_audio
    name: "Billy Bass Speaker"
    id: billy_player
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO22
    on_state:
      then:
        - lambda: |-
            id(mouth_sync).start_sync();

# ========== MICROPHONE ==========
# microphone:
#   - platform: i2s_audio
#     id: inmp441_mic
#     i2s_audio_id: i2s_mic
#     adc_type: external
#     i2s_din_pin: GPIO17
#     pdm: false

# sensor:
#   - platform: sound_level
#     id: audio_rms_sensor
#     microphone: inmp441_mic
#     passive: false
#     peak:
#       name: "Audio Peak Amplitude"
#     rms:
#       name: "Audio RMS Amplitude"
#       id: audio_rms_amplitude

# ========== BILLY MOUTH SYNC ==========
billy_mouth_sync:
  id: mouth_sync
  mouth_motor_id: mouth_motor
  #audio_rms_id: audio_rms_amplitude

# ========== MOUTH MOTOR ==========
output:
  - platform: ledc
    pin: GPIO14
    id: motor_forward_pin
  - platform: ledc
    pin: GPIO27
    id: motor_reverse_pin

fan:
  - platform: hbridge
    id: mouth_motor
    name: "Billy Bass Mouth"
    pin_a: motor_forward_pin
    pin_b: motor_reverse_pin
    decay_mode: fast
